param([string]$Source="D:\Hackathon\hackathon\hackathon.pptx",[string]$Output="D:\Hackathon\hackathon\hackathon_demo_deck.pptx")
$ErrorActionPreference='Stop';$Build=Join-Path $PSScriptRoot 'work';if(Test-Path $Build){Remove-Item $Build -Recurse -Force};New-Item -ItemType Directory $Build|Out-Null;$Archive=Join-Path $PSScriptRoot 'source.zip';Copy-Item $Source $Archive -Force;Expand-Archive $Archive $Build -Force;Remove-Item $Archive -Force
function E($s){[Security.SecurityElement]::Escape($s)}
function T($i,$s,$x,$y,$w,$h,$z=1800,$c='FFFFFF',$b='0'){'<p:sp><p:nvSpPr><p:cNvPr id="{0}" name="t{0}"/><p:cNvSpPr txBox="1"/><p:nvPr/></p:nvSpPr><p:spPr><a:xfrm><a:off x="{2}" y="{3}"/><a:ext cx="{4}" cy="{5}"/></a:xfrm><a:prstGeom prst="rect"><a:avLst/></a:prstGeom><a:noFill/><a:ln><a:noFill/></a:ln></p:spPr><p:txBody><a:bodyPr/><a:lstStyle/><a:p><a:r><a:rPr sz="{6}" b="{8}"><a:solidFill><a:srgbClr val="{7}"/></a:solidFill><a:latin typeface="Aptos"/></a:rPr><a:t>{1}</a:t></a:r></a:p></p:txBody></p:sp>' -f $i,(E $s),$x,$y,$w,$h,$z,$c,$b}
function B($i,$s,$x,$y,$w,$h,$c='1A3A56'){'<p:sp><p:nvSpPr><p:cNvPr id="{0}" name="b{0}"/><p:cNvSpPr/><p:nvPr/></p:nvSpPr><p:spPr><a:xfrm><a:off x="{2}" y="{3}"/><a:ext cx="{4}" cy="{5}"/></a:xfrm><a:prstGeom prst="roundRect"><a:avLst/></a:prstGeom><a:solidFill><a:srgbClr val="{6}"/></a:solidFill><a:ln><a:noFill/></a:ln></p:spPr><p:txBody><a:bodyPr anchor="ctr"/><a:lstStyle/><a:p><a:pPr algn="ctr"/><a:r><a:rPr sz="1500" b="1"><a:solidFill><a:srgbClr val="FFFFFF"/></a:solidFill><a:latin typeface="Aptos"/></a:rPr><a:t>{1}</a:t></a:r></a:p></p:txBody></p:sp>' -f $i,(E $s),$x,$y,$w,$h,$c}
function S($a){'<?xml version="1.0" encoding="UTF-8" standalone="yes"?><p:sld xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" xmlns:p="http://schemas.openxmlformats.org/presentationml/2006/main"><p:cSld><p:spTree><p:nvGrpSpPr><p:cNvPr id="1" name=""/><p:cNvGrpSpPr/><p:nvPr/></p:nvGrpSpPr><p:grpSpPr/><p:sp><p:nvSpPr><p:cNvPr id="2" name="bg"/><p:cNvSpPr/><p:nvPr/></p:nvSpPr><p:spPr><a:xfrm><a:off x="0" y="0"/><a:ext cx="12192000" cy="6858000"/></a:xfrm><a:prstGeom prst="rect"><a:avLst/></a:prstGeom><a:solidFill><a:srgbClr val="10243A"/></a:solidFill><a:ln><a:noFill/></a:ln></p:spPr><p:txBody><a:bodyPr/><a:lstStyle/><a:p/></p:txBody></p:sp>{0}</p:spTree></p:cSld><p:clrMapOvr><a:masterClrMapping/></p:clrMapOvr></p:sld>' -f $a}
function Header($title,$sub,$n){(T 3 $title 650000 400000 10800000 500000 2900 'FFFFFF' '1')+(T 4 $sub 650000 1050000 10800000 360000 1450 '93A9B8')+(T 5 ('NUS-ISS Show Me Your Agent | '+$n.ToString('00')) 650000 6400000 5000000 150000 950 '93A9B8')}
$data=@(
@('AI Production Planning Assistant','A trustworthy agent for manufacturing planning','Understand changes. Simulate consequences. Propose verifiable actions.'),
@('Planning challenges in manufacturing','Production planning changes every day','Order changes | Material shortage | Machine outage | Due-date changes'),
@('Project goals and boundaries','A helpful agent with explicit authority limits','Agent can understand, simulate and propose. Agent cannot invent facts, bypass constraints or skip approval.'),
@('From user input to trusted decisions','How the layers connect','Planner UI > API Boundary > Orchestration > LLM Agent > Tool Registry > Deterministic Core > Plan Governance'),
@('Context, model and tools','Stateful orchestration with schema-validated handoffs','Business state + task + recent tool results > Context Manager > structured model action > controlled tool result'),
@('Why critical decisions do not belong to the LLM','LLM communication, deterministic computation','LLM: language, translation, explanation, next-tool selection. Core: constraints, scheduling, risk and impact.'),
@('Demo 1: Govern incoming data','Play Video 1: Import and Mapping | 2:00','Spreadsheet > mapping proposal > human confirmation > reversible batch'),
@('Demo 2: Generate a constrained plan','Play Video 2: Dashboard and Schedule | 2:30','Show CNC-01, material scarcity, Gantt, FCFS baseline and unblock conditions.'),
@('Demo 3: Human approval','Play Video 3: Approval | 1:30','PENDING_APPROVAL > APPROVE / MODIFY / REJECT > ACTIVE'),
@('Demo 4: Risk radar','Play Video 4: Risks | 1:30','Bottleneck, material runout, zero-slack order and capacity risk.'),
@('Demo 5: What-if simulation','Play Video 5: What-if and Proposal | 3:30','Natural language > structured scenario > sandbox simulation > formal proposal.'),
@('Trace and accountability','Optional Video 6: Trace Viewer | 0:45','Every run records task, context, tool calls, results, proposal and approval.'),
@('Trustworthiness evidence','What prevents the system from doing the wrong thing?','Verified input | deterministic planning | sandbox simulation | approval | versioning | trace and audit'),
@('Value and next steps','Operational, governance and commercial value','Faster replanning. Safer automation. Planner Copilot > ERP/MES integration > multi-site planning.')
)
$slides=@();for($j=0;$j -lt $data.Count;$j++){$d=$data[$j];$b=Header $d[0] $d[1] ($j+1);if($j -ge 6 -and $j -le 10){$b+=B 10 ('VIDEO PLACEHOLDER: '+$d[1]) 900000 2100000 7000000 2800000 '17344E';$b+=T 11 'Evidence to narrate' 8300000 2200000 2800000 350000 1800 'FFC857' '1';$b+=T 12 $d[2] 8300000 2900000 2800000 1200000 1500 'FFFFFF'}else{$b+=B 10 $d[2] 1100000 2400000 10000000 1600000 $(if($j -eq 4){'42C7B5'}else{'1A3A56'});$b+=T 11 'Presenter cue: explain why this layer exists and how it protects the next layer.' 1500000 4800000 9000000 350000 1550 'FFC857' '1'};$slides+=S $b}
$sp=Join-Path $Build 'ppt\slides';$rp=Join-Path $sp '_rels';$rel=Get-Content (Join-Path $rp 'slide1.xml.rels') -Raw;for($i=0;$i -lt $slides.Count;$i++){[IO.File]::WriteAllText((Join-Path $sp ('slide'+($i+1)+'.xml')),$slides[$i],[Text.UTF8Encoding]::new($false));[IO.File]::WriteAllText((Join-Path $rp ('slide'+($i+1)+'.xml.rels')),$rel,[Text.UTF8Encoding]::new($false))}
[xml]$ct=Get-Content -LiteralPath (Join-Path $Build '[Content_Types].xml');for($i=2;$i -le 14;$i++){$n=$ct.CreateElement('Override',$ct.DocumentElement.NamespaceURI);$n.SetAttribute('PartName',('/ppt/slides/slide'+$i+'.xml'));$n.SetAttribute('ContentType','application/vnd.openxmlformats-officedocument.presentationml.slide+xml');[void]$ct.DocumentElement.AppendChild($n)};$ct.Save((Join-Path $Build '[Content_Types].xml'))
[xml]$p=Get-Content (Join-Path $Build 'ppt\presentation.xml');$ns=New-Object Xml.XmlNamespaceManager($p.NameTable);$ns.AddNamespace('p','http://schemas.openxmlformats.org/presentationml/2006/main');$lst=$p.SelectSingleNode('//p:sldIdLst',$ns);for($i=2;$i -le 14;$i++){$n=$p.CreateElement('p','sldId',$lst.NamespaceURI);$n.SetAttribute('id',[string](255+$i));$n.SetAttribute('id','http://schemas.openxmlformats.org/officeDocument/2006/relationships',('rId'+(10+$i)));[void]$lst.AppendChild($n)};$p.Save((Join-Path $Build 'ppt\presentation.xml'))
[xml]$r=Get-Content (Join-Path $Build 'ppt\_rels\presentation.xml.rels');for($i=2;$i -le 14;$i++){$n=$r.CreateElement('Relationship',$r.DocumentElement.NamespaceURI);$n.SetAttribute('Id',('rId'+(10+$i)));$n.SetAttribute('Type','http://schemas.openxmlformats.org/officeDocument/2006/relationships/slide');$n.SetAttribute('Target',('slides/slide'+$i+'.xml'));[void]$r.DocumentElement.AppendChild($n)};$r.Save((Join-Path $Build 'ppt\_rels\presentation.xml.rels'))
if(Test-Path $Output){Remove-Item $Output -Force};Compress-Archive -Path (Join-Path $Build '*') -DestinationPath ($Output+'.zip') -Force;Move-Item ($Output+'.zip') $Output -Force
