param([string]$Source="D:\Hackathon\hackathon\hackathon_demo_deck.pptx",[string]$Output="D:\Hackathon\hackathon\hackathon_demo_deck_cn.pptx")
$ErrorActionPreference='Stop';$Build=Join-Path $PSScriptRoot 'work';if(Test-Path $Build){Remove-Item $Build -Recurse -Force};New-Item -ItemType Directory $Build|Out-Null;$Archive=Join-Path $PSScriptRoot 'source.zip';Copy-Item $Source $Archive -Force;Expand-Archive $Archive $Build -Force;Remove-Item $Archive -Force
function E($s){[Security.SecurityElement]::Escape($s)}
function T($i,$s,$x,$y,$w,$h,$z=1800,$c='FFFFFF',$b='0'){'<p:sp><p:nvSpPr><p:cNvPr id="{0}" name="t{0}"/><p:cNvSpPr txBox="1"/><p:nvPr/></p:nvSpPr><p:spPr><a:xfrm><a:off x="{2}" y="{3}"/><a:ext cx="{4}" cy="{5}"/></a:xfrm><a:prstGeom prst="rect"><a:avLst/></a:prstGeom><a:noFill/><a:ln><a:noFill/></a:ln></p:spPr><p:txBody><a:bodyPr/><a:lstStyle/><a:p><a:r><a:rPr sz="{6}" b="{8}"><a:solidFill><a:srgbClr val="{7}"/></a:solidFill><a:latin typeface="Aptos"/></a:rPr><a:t>{1}</a:t></a:r></a:p></p:txBody></p:sp>' -f $i,(E $s),$x,$y,$w,$h,$z,$c,$b}
function B($i,$s,$x,$y,$w,$h,$c='1A3A56'){'<p:sp><p:nvSpPr><p:cNvPr id="{0}" name="b{0}"/><p:cNvSpPr/><p:nvPr/></p:nvSpPr><p:spPr><a:xfrm><a:off x="{2}" y="{3}"/><a:ext cx="{4}" cy="{5}"/></a:xfrm><a:prstGeom prst="roundRect"><a:avLst/></a:prstGeom><a:solidFill><a:srgbClr val="{6}"/></a:solidFill><a:ln><a:noFill/></a:ln></p:spPr><p:txBody><a:bodyPr anchor="ctr"/><a:lstStyle/><a:p><a:pPr algn="ctr"/><a:r><a:rPr sz="1500" b="1"><a:solidFill><a:srgbClr val="FFFFFF"/></a:solidFill><a:latin typeface="Aptos"/></a:rPr><a:t>{1}</a:t></a:r></a:p></p:txBody></p:sp>' -f $i,(E $s),$x,$y,$w,$h,$c}
function P($i,$rid,$x,$y,$w,$h){'<p:pic><p:nvPicPr><p:cNvPr id="{0}" name="image{0}"/><p:cNvPicPr/><p:nvPr/></p:nvPicPr><p:blipFill><a:blip r:embed="{1}"/><a:stretch><a:fillRect/></a:stretch></p:blipFill><p:spPr><a:xfrm><a:off x="{2}" y="{3}"/><a:ext cx="{4}" cy="{5}"/></a:xfrm><a:prstGeom prst="rect"><a:avLst/></a:prstGeom></p:spPr></p:pic>' -f $i,$rid,$x,$y,$w,$h}
function S($a){'<?xml version="1.0" encoding="UTF-8" standalone="yes"?><p:sld xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" xmlns:p="http://schemas.openxmlformats.org/presentationml/2006/main"><p:cSld><p:spTree><p:nvGrpSpPr><p:cNvPr id="1" name=""/><p:cNvGrpSpPr/><p:nvPr/></p:nvGrpSpPr><p:grpSpPr/><p:sp><p:nvSpPr><p:cNvPr id="2" name="bg"/><p:cNvSpPr/><p:nvPr/></p:nvSpPr><p:spPr><a:xfrm><a:off x="0" y="0"/><a:ext cx="12192000" cy="6858000"/></a:xfrm><a:prstGeom prst="rect"><a:avLst/></a:prstGeom><a:solidFill><a:srgbClr val="10243A"/></a:solidFill><a:ln><a:noFill/></a:ln></p:spPr><p:txBody><a:bodyPr/><a:lstStyle/><a:p/></p:txBody></p:sp>{0}</p:spTree></p:cSld><p:clrMapOvr><a:masterClrMapping/></p:clrMapOvr><p:transition spd="med" advClick="1"><p:fade/></p:transition></p:sld>' -f $a}
function Header($title,$sub,$n){(T 3 $title 650000 400000 10800000 500000 2900 'FFFFFF' '1')+(T 4 $sub 650000 1050000 10800000 360000 1450 '93A9B8')+(T 5 ('NUS-ISS Show Me Your Agent | '+$n.ToString('00')) 650000 6400000 5000000 150000 950 '93A9B8')}
$data=@(
@('AI 生产计划助手','在频繁变化中，把计划做得更快、更稳、更可追溯','理解变化｜模拟影响｜提出可验证的行动建议'),
@('生产计划为什么如此困难？','一个变化，往往会同时牵动交期、设备、物料与产能','订单插单｜物料短缺｜设备停机｜交期压力'),
@('我们的目标：可信的计划协作助手','帮助计划员做判断，但不替代计划员承担最终决策','理解｜模拟｜建议；不编造、不越权、不跳过审批'),
@('从自然语言到可信决策','每一层只接收它需要的信息，并为下一层建立边界','计划员界面 → API 边界 → 编排层 → LLM 智能体 → 工具注册表 → 确定性排产核心 → 审批治理'),
@('上下文不是“聊天记录”','每次调用前，系统为当前任务重新组织必要且已验证的事实','业务状态 + 当前任务 + 最近工具结果 + 历史摘要 → Context Manager → 结构化动作'),
@('LLM 与确定性核心：各做最擅长的事','语言理解与严谨计算分工协作，避免概率输出成为生产事实','LLM：理解、解释、选择工具；核心：约束、排程、风险、影响计算'),
@('演示一：受治理的数据导入','播放录屏 1｜导入与字段映射｜2:00','文件上传 → 映射建议 → 人工确认 → 可回滚导入批次'),
@('演示二：约束下生成计划','播放录屏 2｜仪表盘与排程｜2:30','聚焦 CNC-01、物料约束、甘特图、阻塞原因与解除条件'),
@('演示三：审批让责任边界可见','播放录屏 3｜审批流｜1:30','待审批 → 批准／修改／拒绝 → 正式生效'),
@('演示四：风险雷达','播放录屏 4｜风险扫描｜1:30','识别瓶颈、物料耗尽、零缓冲订单与产能风险'),
@('演示五：What-if 情景推演','播放录屏 5｜故障推演与提案｜3:30','自然语言 → 结构化场景 → 沙盒模拟 → 影响对比 → 正式提案'),
@('全过程可追溯','可选录屏 6｜Trace Viewer｜0:45','任务、上下文、工具调用、结果、提案与审批结论全部留痕'),
@('可信性来自架构，而不是一句承诺','每道防线都阻止不确定的输出直接进入生产计划','输入验证｜确定性计算｜沙盒模拟｜审批关口｜版本管理｜审计追踪'),
@('价值与下一步','从更快重排计划，走向与 ERP／MES 集成的计划协作平台','降低重排时间｜提高决策可解释性｜为多工厂协同做好准备')
)
$slides=@();for($j=0;$j -lt $data.Count;$j++){$d=$data[$j];$b='';if($j -eq 0){$b+=P 50 'rId2' 0 0 12192000 6858000};if($j -eq 3){$b+=P 50 'rId2' 1500000 1800000 9200000 4300000};if($j -eq 10){$b+=P 50 'rId2' 0 1650000 12192000 4800000};$b+=Header $d[0] $d[1] ($j+1);if($j -eq 0){$b+=B 10 $d[2] 650000 2800000 4600000 650000 '17344E';$b+=T 11 'NUS-ISS Show Me Your Agent' 700000 3950000 4000000 250000 1500 'FFC857' '1'}elseif($j -eq 3 -or $j -eq 10){$b+=B 10 $d[2] 850000 5550000 10400000 550000 '17344E'}elseif($j -ge 6 -and $j -le 10){$b+=B 10 ('录屏区域｜'+$d[1]) 850000 2100000 6900000 2800000 '17344E';$b+=T 11 '这一段要让评委看到' 8200000 2200000 3000000 350000 1800 'FFC857' '1';$b+=T 12 $d[2] 8200000 2850000 2900000 1250000 1500 'FFFFFF'}else{$b+=B 10 $d[2] 1100000 2450000 10000000 1400000 $(if($j -eq 4){'197D79'}else{'1A3A56'});$b+=T 11 '叙述提示：先说明这一层解决什么问题，再说明它如何约束或支撑下一层。' 1500000 4750000 9000000 380000 1450 'FFC857' '1'};$slides+=S $b}
$sp=Join-Path $Build 'ppt\slides';$rp=Join-Path $sp '_rels';$rel=Get-Content (Join-Path $rp 'slide1.xml.rels') -Raw;$media=Join-Path $Build 'ppt\media';New-Item -ItemType Directory $media -Force|Out-Null;Copy-Item (Join-Path (Split-Path $PSScriptRoot) 'presentation_assets\cover-hero.png') (Join-Path $media 'cover-hero.png') -Force;Copy-Item (Join-Path (Split-Path $PSScriptRoot) 'presentation_assets\architecture-hero.png') (Join-Path $media 'architecture-hero.png') -Force;Copy-Item (Join-Path (Split-Path $PSScriptRoot) 'presentation_assets\whatif-hero.png') (Join-Path $media 'whatif-hero.png') -Force;for($i=0;$i -lt $slides.Count;$i++){$r=$rel;if($i -in @(0,3,10)){$file=@('cover-hero.png','architecture-hero.png','whatif-hero.png')[@(0,3,10).IndexOf($i)];$img='<Relationship Id="rId2" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/image" Target="../media/'+$file+'"/>';$r=$rel.Replace('</Relationships>',$img+'</Relationships>')}[IO.File]::WriteAllText((Join-Path $sp ('slide'+($i+1)+'.xml')),$slides[$i],[Text.UTF8Encoding]::new($false));[IO.File]::WriteAllText((Join-Path $rp ('slide'+($i+1)+'.xml.rels')),$r,[Text.UTF8Encoding]::new($false))}
[xml]$ct=Get-Content -LiteralPath (Join-Path $Build '[Content_Types].xml');$png=$ct.CreateElement('Default',$ct.DocumentElement.NamespaceURI);$png.SetAttribute('Extension','png');$png.SetAttribute('ContentType','image/png');[void]$ct.DocumentElement.AppendChild($png);for($i=2;$i -le 14;$i++){$n=$ct.CreateElement('Override',$ct.DocumentElement.NamespaceURI);$n.SetAttribute('PartName',('/ppt/slides/slide'+$i+'.xml'));$n.SetAttribute('ContentType','application/vnd.openxmlformats-officedocument.presentationml.slide+xml');[void]$ct.DocumentElement.AppendChild($n)};$ct.Save((Join-Path $Build '[Content_Types].xml'))
[xml]$p=Get-Content (Join-Path $Build 'ppt\presentation.xml');$ns=New-Object Xml.XmlNamespaceManager($p.NameTable);$ns.AddNamespace('p','http://schemas.openxmlformats.org/presentationml/2006/main');$lst=$p.SelectSingleNode('//p:sldIdLst',$ns);for($i=2;$i -le 14;$i++){$n=$p.CreateElement('p','sldId',$lst.NamespaceURI);$n.SetAttribute('id',[string](255+$i));$n.SetAttribute('id','http://schemas.openxmlformats.org/officeDocument/2006/relationships',('rId'+(10+$i)));[void]$lst.AppendChild($n)};$p.Save((Join-Path $Build 'ppt\presentation.xml'))
[xml]$r=Get-Content (Join-Path $Build 'ppt\_rels\presentation.xml.rels');for($i=2;$i -le 14;$i++){$n=$r.CreateElement('Relationship',$r.DocumentElement.NamespaceURI);$n.SetAttribute('Id',('rId'+(10+$i)));$n.SetAttribute('Type','http://schemas.openxmlformats.org/officeDocument/2006/relationships/slide');$n.SetAttribute('Target',('slides/slide'+$i+'.xml'));[void]$r.DocumentElement.AppendChild($n)};$r.Save((Join-Path $Build 'ppt\_rels\presentation.xml.rels'))
if(Test-Path $Output){Remove-Item $Output -Force};Compress-Archive -Path (Join-Path $Build '*') -DestinationPath ($Output+'.zip') -Force;Move-Item ($Output+'.zip') $Output -Force
