"""initial schema: all 35 tables from design.md Data Models sections 2-7

Revision ID: 0001_initial_schema
Revises:
Create Date: 2026-09-16

This is the ONE initial revision. tasks.md 1.2 requires the whole schema to be
built at once rather than in batches, so there is deliberately no second
"add remaining tables" revision to follow.

Generated by `alembic revision --autogenerate` against app.db.models.Base.metadata
and then reviewed. Autogenerate was used on purpose instead of hand-writing 35
create_table calls: it guarantees the migration and the models agree on constraint
names, server defaults and index predicates from the first commit.
tests/structure/test_schema_matches_models.py keeps them in agreement afterwards.

Three things worth knowing when reading the generated body:

1. The two partial unique indexes (ux_active_per_day, ux_pending_per_day) carry
   BOTH sqlite_where and postgresql_where. They are the structural enforcement of
   R11.8 / R12.6 - at most one ACTIVE and one PENDING_APPROVAL plan per
   production_date - and property 15 asserts the ACTIVE count stays <= 1.
2. input_snapshots is created with sqlite_autoincrement=True. Without it SQLite
   reuses rowids of deleted rows and the version number stops being monotonic,
   which would silently break the staleness check in R12.1.
3. There is no entity_change_log table and audit_log has no entry_hash/prev_hash
   columns. Both were moved out of scope (requirements section 3 rejection list),
   not forgotten.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0001_initial_schema"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table('audit_log',
    sa.Column('audit_id', sa.String(), nullable=False),
    sa.Column('event_category', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('actor', sa.String(), nullable=False),
    sa.Column('subject_type', sa.String(), nullable=True),
    sa.Column('subject_id', sa.String(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('trace_id', sa.String(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('audit_id', name=op.f('pk_audit_log'))
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index('ix_audit_category_time', ['event_category', 'occurred_at'], unique=False)
        batch_op.create_index('ix_audit_subject', ['subject_type', 'subject_id'], unique=False)

    op.create_table('input_snapshots',
    sa.Column('snapshot_version', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('trigger', sa.String(), nullable=False),
    sa.Column('fingerprint', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('snapshot_version', name=op.f('pk_input_snapshots')),
    sqlite_autoincrement=True
    )
    op.create_table('llm_cache',
    sa.Column('content_hash', sa.String(), nullable=False),
    sa.Column('agent', sa.String(), nullable=False),
    sa.Column('response_json', sa.JSON(), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('hit_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.PrimaryKeyConstraint('content_hash', name=op.f('pk_llm_cache'))
    )
    op.create_table('machines',
    sa.Column('machine_id', sa.String(), nullable=False),
    sa.Column('machine_type', sa.String(), nullable=False),
    sa.Column('capabilities', sa.JSON(), server_default=sa.text("'[]'"), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('available_start', sa.DateTime(), nullable=False),
    sa.Column('available_end', sa.DateTime(), nullable=False),
    sa.Column('rate_multiplier', sa.Numeric(), server_default=sa.text('(1.0)'), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('record_status', sa.String(), server_default=sa.text("'ACTIVE'"), nullable=False),
    sa.Column('import_batch_id', sa.String(), nullable=True),
    sa.Column('last_updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('rate_multiplier > 0', name=op.f('ck_machines_rate_multiplier_positive')),
    sa.PrimaryKeyConstraint('machine_id', name=op.f('pk_machines'))
    )
    op.create_table('materials',
    sa.Column('material_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('unit', sa.String(), nullable=False),
    sa.Column('quantity_available', sa.Numeric(), nullable=False),
    sa.Column('reserved_quantity', sa.Numeric(), server_default=sa.text('0'), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('record_status', sa.String(), server_default=sa.text("'ACTIVE'"), nullable=False),
    sa.Column('import_batch_id', sa.String(), nullable=True),
    sa.Column('last_updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('material_id', name=op.f('pk_materials'))
    )
    op.create_table('preference_rules',
    sa.Column('rule_id', sa.String(), nullable=False),
    sa.Column('human_text', sa.String(), nullable=False),
    sa.Column('structured_form', sa.JSON(), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('low_evidence', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('rule_id', name=op.f('pk_preference_rules'))
    )
    with op.batch_alter_table('preference_rules', schema=None) as batch_op:
        batch_op.create_index('ix_pref_rules_enabled', ['enabled'], unique=False)

    op.create_table('settings',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_settings'))
    )
    op.create_table('traces',
    sa.Column('trace_id', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('mode', sa.String(), nullable=False),
    sa.Column('agent', sa.String(), nullable=True),
    sa.Column('trigger_source', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('outcome', sa.String(), nullable=True),
    sa.Column('step_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('total_input_tokens', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('total_output_tokens', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('estimated_usd', sa.Numeric(), server_default=sa.text('0'), nullable=False),
    sa.Column('result_ref', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('trace_id', name=op.f('pk_traces'))
    )
    with op.batch_alter_table('traces', schema=None) as batch_op:
        batch_op.create_index('ix_traces_mode_started', ['mode', 'started_at'], unique=False)

    op.create_table('workers',
    sa.Column('worker_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('skills', sa.JSON(), server_default=sa.text("'[]'"), nullable=False),
    sa.Column('shift_start', sa.DateTime(), nullable=False),
    sa.Column('shift_end', sa.DateTime(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('record_status', sa.String(), server_default=sa.text("'ACTIVE'"), nullable=False),
    sa.Column('import_batch_id', sa.String(), nullable=True),
    sa.Column('last_updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('worker_id', name=op.f('pk_workers'))
    )
    op.create_table('changeover_rules',
    sa.Column('rule_id', sa.String(), nullable=False),
    sa.Column('machine_id', sa.String(), nullable=True),
    sa.Column('from_product_id', sa.String(), nullable=True),
    sa.Column('to_product_id', sa.String(), nullable=True),
    sa.Column('changeover_minutes', sa.Integer(), nullable=False),
    sa.Column('specificity', sa.Integer(), nullable=False),
    sa.CheckConstraint('changeover_minutes >= 0', name=op.f('ck_changeover_rules_changeover_non_negative')),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.machine_id'], name=op.f('fk_changeover_rules_machine_id_machines')),
    sa.PrimaryKeyConstraint('rule_id', name=op.f('pk_changeover_rules'))
    )
    with op.batch_alter_table('changeover_rules', schema=None) as batch_op:
        batch_op.create_index('ix_changeover_lookup', ['machine_id', 'from_product_id', 'to_product_id'], unique=False)

    op.create_table('import_batches',
    sa.Column('batch_id', sa.String(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('file_checksum', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('proposed_mapping', sa.JSON(), nullable=False),
    sa.Column('accepted_mapping', sa.JSON(), nullable=True),
    sa.Column('operator_decisions', sa.JSON(), nullable=True),
    sa.Column('normalisations', sa.JSON(), nullable=True),
    sa.Column('unparsed_cells', sa.JSON(), server_default=sa.text("'[]'"), nullable=False),
    sa.Column('formula_columns', sa.JSON(), server_default=sa.text("'[]'"), nullable=False),
    sa.Column('ingestion_report', sa.JSON(), nullable=True),
    sa.Column('trace_id', sa.String(), nullable=True),
    sa.Column('imported_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['trace_id'], ['traces.trace_id'], name=op.f('fk_import_batches_trace_id_traces')),
    sa.PrimaryKeyConstraint('batch_id', name=op.f('pk_import_batches'))
    )
    with op.batch_alter_table('import_batches', schema=None) as batch_op:
        batch_op.create_index('ix_batch_checksum', ['file_checksum'], unique=False)

    op.create_table('incoming_deliveries',
    sa.Column('delivery_id', sa.String(), nullable=False),
    sa.Column('material_id', sa.String(), nullable=False),
    sa.Column('quantity', sa.Numeric(), nullable=False),
    sa.Column('eta', sa.DateTime(), nullable=False),
    sa.Column('confirmed', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['materials.material_id'], name=op.f('fk_incoming_deliveries_material_id_materials')),
    sa.PrimaryKeyConstraint('delivery_id', name=op.f('pk_incoming_deliveries'))
    )
    with op.batch_alter_table('incoming_deliveries', schema=None) as batch_op:
        batch_op.create_index('ix_incoming_material_eta', ['material_id', 'eta'], unique=False)

    op.create_table('production_plans',
    sa.Column('plan_id', sa.String(), nullable=False),
    sa.Column('production_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('feasibility', sa.String(), nullable=False),
    sa.Column('plan_version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('input_snapshot_version', sa.Integer(), nullable=False),
    sa.Column('origin', sa.String(), nullable=False),
    sa.Column('supersedes_plan_id', sa.String(), nullable=True),
    sa.Column('superseded_by_plan_id', sa.String(), nullable=True),
    sa.Column('generated_by_trace_id', sa.String(), nullable=True),
    sa.Column('disruption_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('rejection_reason', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['generated_by_trace_id'], ['traces.trace_id'], name=op.f('fk_production_plans_generated_by_trace_id_traces')),
    sa.ForeignKeyConstraint(['input_snapshot_version'], ['input_snapshots.snapshot_version'], name=op.f('fk_production_plans_input_snapshot_version_input_snapshots')),
    sa.ForeignKeyConstraint(['superseded_by_plan_id'], ['production_plans.plan_id'], name=op.f('fk_production_plans_superseded_by_plan_id_production_plans')),
    sa.ForeignKeyConstraint(['supersedes_plan_id'], ['production_plans.plan_id'], name=op.f('fk_production_plans_supersedes_plan_id_production_plans')),
    sa.PrimaryKeyConstraint('plan_id', name=op.f('pk_production_plans'))
    )
    with op.batch_alter_table('production_plans', schema=None) as batch_op:
        batch_op.create_index('ix_plans_date_status', ['production_date', 'status'], unique=False)
        batch_op.create_index('ux_active_per_day', ['production_date'], unique=True, sqlite_where=sa.text("status = 'ACTIVE'"), postgresql_where=sa.text("status = 'ACTIVE'"))
        batch_op.create_index('ux_pending_per_day', ['production_date'], unique=True, sqlite_where=sa.text("status = 'PENDING_APPROVAL'"), postgresql_where=sa.text("status = 'PENDING_APPROVAL'"))

    op.create_table('trace_steps',
    sa.Column('step_id', sa.String(), nullable=False),
    sa.Column('trace_id', sa.String(), nullable=False),
    sa.Column('step_index', sa.Integer(), nullable=False),
    sa.Column('step_kind', sa.String(), nullable=False),
    sa.Column('decision_reason', sa.String(), nullable=True),
    sa.Column('input_digest', sa.String(), nullable=True),
    sa.Column('output_digest', sa.String(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('input_tokens', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('output_tokens', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.ForeignKeyConstraint(['trace_id'], ['traces.trace_id'], name=op.f('fk_trace_steps_trace_id_traces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('step_id', name=op.f('pk_trace_steps')),
    sa.UniqueConstraint('trace_id', 'step_index', name='uq_trace_steps_trace_index')
    )
    op.create_table('baseline_comparisons',
    sa.Column('plan_id', sa.String(), nullable=False),
    sa.Column('baseline_plan_id', sa.String(), nullable=False),
    sa.Column('snapshot_version', sa.Integer(), nullable=False),
    sa.Column('on_time_rate', sa.Numeric(), nullable=False),
    sa.Column('baseline_on_time_rate', sa.Numeric(), nullable=False),
    sa.Column('total_tardiness_minutes', sa.Integer(), nullable=False),
    sa.Column('baseline_total_tardiness_minutes', sa.Integer(), nullable=False),
    sa.Column('late_order_count', sa.Integer(), nullable=False),
    sa.Column('baseline_late_order_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['baseline_plan_id'], ['production_plans.plan_id'], name=op.f('fk_baseline_comparisons_baseline_plan_id_production_plans')),
    sa.ForeignKeyConstraint(['plan_id'], ['production_plans.plan_id'], name=op.f('fk_baseline_comparisons_plan_id_production_plans'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('plan_id', name=op.f('pk_baseline_comparisons'))
    )
    op.create_table('disruptions',
    sa.Column('disruption_id', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('reported_at', sa.DateTime(), nullable=False),
    sa.Column('registered_at', sa.DateTime(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('active_plan_id', sa.String(), nullable=False),
    sa.Column('trace_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['active_plan_id'], ['production_plans.plan_id'], name=op.f('fk_disruptions_active_plan_id_production_plans')),
    sa.ForeignKeyConstraint(['trace_id'], ['traces.trace_id'], name=op.f('fk_disruptions_trace_id_traces')),
    sa.PrimaryKeyConstraint('disruption_id', name=op.f('pk_disruptions'))
    )
    op.create_table('import_row_provenance',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('batch_id', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.Column('source_row_number', sa.Integer(), nullable=False),
    sa.Column('raw_row', sa.JSON(), nullable=False),
    sa.Column('overwritten_payload', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['import_batches.batch_id'], name=op.f('fk_import_row_provenance_batch_id_import_batches'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_import_row_provenance')),
    sa.UniqueConstraint('batch_id', 'entity_type', 'entity_id', name='uq_provenance_batch_entity')
    )
    op.create_table('objective_breakdowns',
    sa.Column('plan_id', sa.String(), nullable=False),
    sa.Column('components', sa.JSON(), nullable=False),
    sa.Column('total_score', sa.Numeric(), nullable=False),
    sa.Column('weights', sa.JSON(), nullable=False),
    sa.Column('preference_contributions', sa.JSON(), nullable=False),
    sa.Column('weight_overrides_applied', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['production_plans.plan_id'], name=op.f('fk_objective_breakdowns_plan_id_production_plans'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('plan_id', name=op.f('pk_objective_breakdowns'))
    )
    op.create_table('plan_approvals',
    sa.Column('approval_id', sa.String(), nullable=False),
    sa.Column('plan_id', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('actor', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('rejection_reason', sa.String(), nullable=True),
    sa.Column('revalidation_result', sa.JSON(), nullable=False),
    sa.Column('modifications', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['production_plans.plan_id'], name=op.f('fk_plan_approvals_plan_id_production_plans')),
    sa.PrimaryKeyConstraint('approval_id', name=op.f('pk_plan_approvals'))
    )
    with op.batch_alter_table('plan_approvals', schema=None) as batch_op:
        batch_op.create_index('ix_approvals_plan', ['plan_id', 'timestamp'], unique=False)

    op.create_table('planner_decisions',
    sa.Column('decision_id', sa.String(), nullable=False),
    sa.Column('plan_id', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('rejection_reason', sa.String(), nullable=True),
    sa.Column('modifications', sa.JSON(), nullable=True),
    sa.Column('objective_breakdown_snapshot', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['production_plans.plan_id'], name=op.f('fk_planner_decisions_plan_id_production_plans')),
    sa.PrimaryKeyConstraint('decision_id', name=op.f('pk_planner_decisions'))
    )
    op.create_table('products',
    sa.Column('product_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('record_status', sa.String(), server_default=sa.text("'ACTIVE'"), nullable=False),
    sa.Column('import_batch_id', sa.String(), nullable=True),
    sa.Column('last_updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['import_batch_id'], ['import_batches.batch_id'], name=op.f('fk_products_import_batch_id_import_batches')),
    sa.PrimaryKeyConstraint('product_id', name=op.f('pk_products'))
    )
    op.create_table('risk_findings',
    sa.Column('finding_id', sa.String(), nullable=False),
    sa.Column('finding_key', sa.String(), nullable=False),
    sa.Column('risk_type', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.Column('metric_value', sa.Numeric(), nullable=False),
    sa.Column('threshold_value', sa.Numeric(), nullable=False),
    sa.Column('affected_order_ids', sa.JSON(), server_default=sa.text("'[]'"), nullable=False),
    sa.Column('narrative', sa.String(), nullable=True),
    sa.Column('narrative_source', sa.String(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('mitigation_plan_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['mitigation_plan_id'], ['production_plans.plan_id'], name=op.f('fk_risk_findings_mitigation_plan_id_production_plans')),
    sa.PrimaryKeyConstraint('finding_id', name=op.f('pk_risk_findings')),
    sa.UniqueConstraint('finding_key', name=op.f('uq_risk_findings_finding_key'))
    )
    with op.batch_alter_table('risk_findings', schema=None) as batch_op:
        batch_op.create_index('ix_risk_unresolved', ['resolved_at', 'severity'], unique=False)

    op.create_table('tool_calls',
    sa.Column('call_id', sa.String(), nullable=False),
    sa.Column('trace_id', sa.String(), nullable=False),
    sa.Column('step_id', sa.String(), nullable=True),
    sa.Column('caller', sa.String(), nullable=False),
    sa.Column('tool_name', sa.String(), nullable=False),
    sa.Column('args_digest', sa.String(), nullable=False),
    sa.Column('args_json', sa.JSON(), nullable=True),
    sa.Column('result_summary', sa.String(), nullable=False),
    sa.Column('result_tokens', sa.Integer(), nullable=False),
    sa.Column('truncated', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('outcome', sa.String(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['step_id'], ['trace_steps.step_id'], name=op.f('fk_tool_calls_step_id_trace_steps')),
    sa.ForeignKeyConstraint(['trace_id'], ['traces.trace_id'], name=op.f('fk_tool_calls_trace_id_traces')),
    sa.PrimaryKeyConstraint('call_id', name=op.f('pk_tool_calls'))
    )
    with op.batch_alter_table('tool_calls', schema=None) as batch_op:
        batch_op.create_index('ix_tool_calls_trace_id', ['trace_id'], unique=False)

    op.create_table('value_metrics',
    sa.Column('metric_id', sa.String(), nullable=False),
    sa.Column('plan_id', sa.String(), nullable=True),
    sa.Column('measured_at', sa.DateTime(), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('labels', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['production_plans.plan_id'], name=op.f('fk_value_metrics_plan_id_production_plans')),
    sa.PrimaryKeyConstraint('metric_id', name=op.f('pk_value_metrics'))
    )
    op.create_table('impact_assessments',
    sa.Column('assessment_id', sa.String(), nullable=False),
    sa.Column('candidate_plan_id', sa.String(), nullable=False),
    sa.Column('baseline_plan_id', sa.String(), nullable=False),
    sa.Column('disruption_id', sa.String(), nullable=True),
    sa.Column('impact_class', sa.String(), nullable=False),
    sa.Column('autonomy_level', sa.String(), nullable=False),
    sa.Column('decisive_predicates', sa.JSON(), nullable=False),
    sa.Column('impact_input', sa.JSON(), nullable=False),
    sa.Column('execution_path', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['baseline_plan_id'], ['production_plans.plan_id'], name=op.f('fk_impact_assessments_baseline_plan_id_production_plans')),
    sa.ForeignKeyConstraint(['candidate_plan_id'], ['production_plans.plan_id'], name=op.f('fk_impact_assessments_candidate_plan_id_production_plans')),
    sa.ForeignKeyConstraint(['disruption_id'], ['disruptions.disruption_id'], name=op.f('fk_impact_assessments_disruption_id_disruptions')),
    sa.PrimaryKeyConstraint('assessment_id', name=op.f('pk_impact_assessments'))
    )
    op.create_table('machine_downtime',
    sa.Column('downtime_id', sa.String(), nullable=False),
    sa.Column('machine_id', sa.String(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('disruption_id', sa.String(), nullable=True),
    sa.CheckConstraint('end_time > start_time', name=op.f('ck_machine_downtime_end_after_start')),
    sa.ForeignKeyConstraint(['disruption_id'], ['disruptions.disruption_id'], name=op.f('fk_machine_downtime_disruption_id_disruptions')),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.machine_id'], name=op.f('fk_machine_downtime_machine_id_machines')),
    sa.PrimaryKeyConstraint('downtime_id', name=op.f('pk_machine_downtime'))
    )
    with op.batch_alter_table('machine_downtime', schema=None) as batch_op:
        batch_op.create_index('ix_downtime_machine_start', ['machine_id', 'start_time'], unique=False)

    op.create_table('operations',
    sa.Column('operation_id', sa.String(), nullable=False),
    sa.Column('product_id', sa.String(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('required_machine_type', sa.String(), nullable=False),
    sa.Column('required_capability', sa.String(), nullable=True),
    sa.Column('required_worker_skill', sa.String(), nullable=False),
    sa.Column('base_processing_time_per_unit', sa.Numeric(), nullable=False),
    sa.Column('setup_time', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.CheckConstraint('sequence BETWEEN 1 AND 3', name=op.f('ck_operations_sequence_range')),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], name=op.f('fk_operations_product_id_products')),
    sa.PrimaryKeyConstraint('operation_id', name=op.f('pk_operations')),
    sa.UniqueConstraint('product_id', 'sequence', name='uq_operations_product_sequence')
    )
    op.create_table('orders',
    sa.Column('order_id', sa.String(), nullable=False),
    sa.Column('product_id', sa.String(), nullable=False),
    sa.Column('quantity', sa.Numeric(), nullable=False),
    sa.Column('due_date', sa.DateTime(), nullable=False),
    sa.Column('promised_date', sa.DateTime(), nullable=True),
    sa.Column('priority', sa.String(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('injection_suspected', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('record_status', sa.String(), server_default=sa.text("'ACTIVE'"), nullable=False),
    sa.Column('import_batch_id', sa.String(), nullable=True),
    sa.Column('source_row_number', sa.Integer(), nullable=True),
    sa.Column('last_updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('quantity > 0', name=op.f('ck_orders_quantity_positive')),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], name=op.f('fk_orders_product_id_products')),
    sa.PrimaryKeyConstraint('order_id', name=op.f('pk_orders'))
    )
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.create_index('ix_orders_priority_due', ['priority', 'due_date', 'order_id'], unique=False)

    op.create_table('preference_rule_sources',
    sa.Column('rule_id', sa.String(), nullable=False),
    sa.Column('decision_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['decision_id'], ['planner_decisions.decision_id'], name=op.f('fk_preference_rule_sources_decision_id_planner_decisions')),
    sa.ForeignKeyConstraint(['rule_id'], ['preference_rules.rule_id'], name=op.f('fk_preference_rule_sources_rule_id_preference_rules'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('rule_id', 'decision_id', name=op.f('pk_preference_rule_sources'))
    )
    op.create_table('product_materials',
    sa.Column('product_id', sa.String(), nullable=False),
    sa.Column('material_id', sa.String(), nullable=False),
    sa.Column('quantity_per_unit', sa.Numeric(), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['materials.material_id'], name=op.f('fk_product_materials_material_id_materials')),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], name=op.f('fk_product_materials_product_id_products')),
    sa.PrimaryKeyConstraint('product_id', 'material_id', name=op.f('pk_product_materials'))
    )
    op.create_table('worker_absences',
    sa.Column('absence_id', sa.String(), nullable=False),
    sa.Column('worker_id', sa.String(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('disruption_id', sa.String(), nullable=True),
    sa.CheckConstraint('end_time > start_time', name=op.f('ck_worker_absences_end_after_start')),
    sa.ForeignKeyConstraint(['disruption_id'], ['disruptions.disruption_id'], name=op.f('fk_worker_absences_disruption_id_disruptions')),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.worker_id'], name=op.f('fk_worker_absences_worker_id_workers')),
    sa.PrimaryKeyConstraint('absence_id', name=op.f('pk_worker_absences'))
    )
    with op.batch_alter_table('worker_absences', schema=None) as batch_op:
        batch_op.create_index('ix_absence_worker_start', ['worker_id', 'start_time'], unique=False)

    op.create_table('auto_applied_changes',
    sa.Column('change_id', sa.String(), nullable=False),
    sa.Column('assessment_id', sa.String(), nullable=False),
    sa.Column('plan_id_before', sa.String(), nullable=False),
    sa.Column('plan_id_after', sa.String(), nullable=False),
    sa.Column('snapshot_before', sa.JSON(), nullable=False),
    sa.Column('snapshot_after', sa.JSON(), nullable=False),
    sa.Column('applied_at', sa.DateTime(), nullable=False),
    sa.Column('reverted', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('reverted_at', sa.DateTime(), nullable=True),
    sa.Column('revert_plan_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['impact_assessments.assessment_id'], name=op.f('fk_auto_applied_changes_assessment_id_impact_assessments')),
    sa.ForeignKeyConstraint(['plan_id_after'], ['production_plans.plan_id'], name=op.f('fk_auto_applied_changes_plan_id_after_production_plans')),
    sa.ForeignKeyConstraint(['plan_id_before'], ['production_plans.plan_id'], name=op.f('fk_auto_applied_changes_plan_id_before_production_plans')),
    sa.ForeignKeyConstraint(['revert_plan_id'], ['production_plans.plan_id'], name=op.f('fk_auto_applied_changes_revert_plan_id_production_plans')),
    sa.PrimaryKeyConstraint('change_id', name=op.f('pk_auto_applied_changes'))
    )
    op.create_table('production_jobs',
    sa.Column('job_id', sa.String(), nullable=False),
    sa.Column('order_id', sa.String(), nullable=False),
    sa.Column('product_id', sa.String(), nullable=False),
    sa.Column('operation_sequence', sa.Integer(), nullable=False),
    sa.Column('predecessor_job_id', sa.String(), nullable=True),
    sa.Column('quantity', sa.Numeric(), nullable=False),
    sa.Column('required_machine_type', sa.String(), nullable=False),
    sa.Column('required_worker_skill', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.order_id'], name=op.f('fk_production_jobs_order_id_orders')),
    sa.ForeignKeyConstraint(['predecessor_job_id'], ['production_jobs.job_id'], name=op.f('fk_production_jobs_predecessor_job_id_production_jobs')),
    sa.PrimaryKeyConstraint('job_id', name=op.f('pk_production_jobs')),
    sa.UniqueConstraint('order_id', 'operation_sequence', name='uq_jobs_order_sequence')
    )
    op.create_table('scheduled_jobs',
    sa.Column('scheduled_job_id', sa.String(), nullable=False),
    sa.Column('plan_id', sa.String(), nullable=False),
    sa.Column('job_id', sa.String(), nullable=False),
    sa.Column('machine_id', sa.String(), nullable=False),
    sa.Column('worker_id', sa.String(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('setup_minutes', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('changeover_minutes', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('locked', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.CheckConstraint('end_time > start_time', name=op.f('ck_scheduled_jobs_end_after_start')),
    sa.ForeignKeyConstraint(['job_id'], ['production_jobs.job_id'], name=op.f('fk_scheduled_jobs_job_id_production_jobs')),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.machine_id'], name=op.f('fk_scheduled_jobs_machine_id_machines')),
    sa.ForeignKeyConstraint(['plan_id'], ['production_plans.plan_id'], name=op.f('fk_scheduled_jobs_plan_id_production_plans'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.worker_id'], name=op.f('fk_scheduled_jobs_worker_id_workers')),
    sa.PrimaryKeyConstraint('scheduled_job_id', name=op.f('pk_scheduled_jobs')),
    sa.UniqueConstraint('plan_id', 'job_id', name='uq_scheduled_plan_job')
    )
    with op.batch_alter_table('scheduled_jobs', schema=None) as batch_op:
        batch_op.create_index('ix_sched_plan_machine_start', ['plan_id', 'machine_id', 'start_time'], unique=False)
        batch_op.create_index('ix_sched_plan_worker_start', ['plan_id', 'worker_id', 'start_time'], unique=False)

    op.create_table('unschedulable_jobs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('plan_id', sa.String(), nullable=False),
    sa.Column('job_id', sa.String(), nullable=False),
    sa.Column('blocking_reason', sa.String(), nullable=False),
    sa.Column('unblock_suggestion', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['production_jobs.job_id'], name=op.f('fk_unschedulable_jobs_job_id_production_jobs')),
    sa.ForeignKeyConstraint(['plan_id'], ['production_plans.plan_id'], name=op.f('fk_unschedulable_jobs_plan_id_production_plans'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_unschedulable_jobs')),
    sa.UniqueConstraint('plan_id', 'job_id', name='uq_unschedulable_plan_job')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('unschedulable_jobs')
    with op.batch_alter_table('scheduled_jobs', schema=None) as batch_op:
        batch_op.drop_index('ix_sched_plan_worker_start')
        batch_op.drop_index('ix_sched_plan_machine_start')

    op.drop_table('scheduled_jobs')
    op.drop_table('production_jobs')
    op.drop_table('auto_applied_changes')
    with op.batch_alter_table('worker_absences', schema=None) as batch_op:
        batch_op.drop_index('ix_absence_worker_start')

    op.drop_table('worker_absences')
    op.drop_table('product_materials')
    op.drop_table('preference_rule_sources')
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index('ix_orders_priority_due')

    op.drop_table('orders')
    op.drop_table('operations')
    with op.batch_alter_table('machine_downtime', schema=None) as batch_op:
        batch_op.drop_index('ix_downtime_machine_start')

    op.drop_table('machine_downtime')
    op.drop_table('impact_assessments')
    op.drop_table('value_metrics')
    with op.batch_alter_table('tool_calls', schema=None) as batch_op:
        batch_op.drop_index('ix_tool_calls_trace_id')

    op.drop_table('tool_calls')
    with op.batch_alter_table('risk_findings', schema=None) as batch_op:
        batch_op.drop_index('ix_risk_unresolved')

    op.drop_table('risk_findings')
    op.drop_table('products')
    op.drop_table('planner_decisions')
    with op.batch_alter_table('plan_approvals', schema=None) as batch_op:
        batch_op.drop_index('ix_approvals_plan')

    op.drop_table('plan_approvals')
    op.drop_table('objective_breakdowns')
    op.drop_table('import_row_provenance')
    op.drop_table('disruptions')
    op.drop_table('baseline_comparisons')
    op.drop_table('trace_steps')
    with op.batch_alter_table('production_plans', schema=None) as batch_op:
        batch_op.drop_index('ux_pending_per_day', sqlite_where=sa.text("status = 'PENDING_APPROVAL'"), postgresql_where=sa.text("status = 'PENDING_APPROVAL'"))
        batch_op.drop_index('ux_active_per_day', sqlite_where=sa.text("status = 'ACTIVE'"), postgresql_where=sa.text("status = 'ACTIVE'"))
        batch_op.drop_index('ix_plans_date_status')

    op.drop_table('production_plans')
    with op.batch_alter_table('incoming_deliveries', schema=None) as batch_op:
        batch_op.drop_index('ix_incoming_material_eta')

    op.drop_table('incoming_deliveries')
    with op.batch_alter_table('import_batches', schema=None) as batch_op:
        batch_op.drop_index('ix_batch_checksum')

    op.drop_table('import_batches')
    with op.batch_alter_table('changeover_rules', schema=None) as batch_op:
        batch_op.drop_index('ix_changeover_lookup')

    op.drop_table('changeover_rules')
    op.drop_table('workers')
    with op.batch_alter_table('traces', schema=None) as batch_op:
        batch_op.drop_index('ix_traces_mode_started')

    op.drop_table('traces')
    op.drop_table('settings')
    with op.batch_alter_table('preference_rules', schema=None) as batch_op:
        batch_op.drop_index('ix_pref_rules_enabled')

    op.drop_table('preference_rules')
    op.drop_table('materials')
    op.drop_table('machines')
    op.drop_table('llm_cache')
    op.drop_table('input_snapshots')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_subject')
        batch_op.drop_index('ix_audit_category_time')

    op.drop_table('audit_log')
    # ### end Alembic commands ###
